version: '3.8'

# This section defines all the services (containers) that make up your application.
services:

  # 1. The App Service
  app-service:
    # 'image' tells Docker Compose to pull this pre-built image from your Harbor registry.
    image: 192.168.223.200:80/bits-mtech/project-app-service:latest
    container_name: app-container
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - auth-service
      - mask-service
      - gemini-service
    restart: always

  # 2. The Auth Service
  auth-service:
    image: 192.168.223.200:80/bits-mtech/project-auth-service:latest
    container_name: auth-container
    env_file:
      - .env
    depends_on:
      - postgres-db-service
    restart: always

  # 3. The PII Masking Service
  mask-service:
    image: 192.168.223.200:80/bits-mtech/project-mask-service:latest
    container_name: mask-container
    env_file:
      - .env
    restart: always

  # 4. The Gemini Worker Service
  gemini-service:
    image: 192.168.223.200:80/bits-mtech/project-gemini-service:latest
    container_name: gemini-service
    env_file:
      - .env
    restart: always

  # 5. The PostgreSQL Database Service (No change needed here)
  postgres-db-service:
    # This image is still pulled from the public Docker Hub.
    image: postgres:17.5-alpine3.22
    container_name: postgres-db-container
    ports:
      - "5432:5432"
    hostname: postgres-db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

# Volumes and Networks (No change needed here)
volumes:
  postgres_data:
    name: postgres-data-volume

networks:
  default:
    name: genai-app-network
